dataset:
  name: US3D
  dataset_path: # path/to/your/dataset
  cache_dir: ./logs/cache_small3d/
  class_weights: [3950915, 54218708, 12096780, 11052226, 1376165, 959579]
  ignored_label_inds: []
  test_result_folder: ./test
  use_cache: true
  steps_per_epoch_train: 500
  steps_per_epoch_valid: 50
  train_dir: ./train
  val_dir: ./validation
  test_dir: ./test
model:
  name: KPFCNN
  ckpt_path: # path/to/your/checkpoint
  KP_extent: 1.2
  KP_influence: linear
  aggregation_mode: sum
  architecture: ['simple',
                'resnetb',
                'resnetb_strided',
                'resnetb',
                'resnetb_strided',
                'resnetb',
                'resnetb_strided',
                'resnetb',
                'resnetb_strided',
                'resnetb',
                'nearest_upsample',
                'unary',
                'nearest_upsample',
                'unary',
                'nearest_upsample',
                'unary',
                'nearest_upsample',
                'unary']
  augment_color: 0.8
  augment_noise: 0.05
  augment_rotation: vertical
  augment_scale_anisotropic: true
  augment_scale_max: 1.1
  augment_scale_min: 0.9
  augment_symmetries:
  - true
  - false
  - false
  batch_limit: 10000
  batch_norm_momentum: 0.02
  batcher: ConcatBatcher
  conv_radius: 2.5
  deform_fitting_mode: point2point
  deform_fitting_power: 1.0
  deform_radius: 6.0
  density_parameter: 5.0
  first_features_dim: 128
  first_subsampling_dl: 2.0
  fixed_kernel_points: center
  ignored_label_inds: []
  in_features_dim: 1
  in_points_dim: 3
  in_radius: 50.0
  lbl_values: [0, 2, 5, 6, 9, 17]
  min_in_points: 5000
  max_in_points: 10000
  modulated: false
  num_classes: 6
  num_kernel_points: 15
  num_layers: 5
  repulse_extent: 1.2
  use_batch_norm: true
pipeline:
  name: SemanticSegmentation
  adam_lr: 0.01
  batch_size: 8
  learning_rate: 0.01
  lr_decays: 0.98477
  deform_lr_factor: 0.1
  main_log_dir: ./logs
  max_epoch: 500
  save_ckpt_freq: 5
  scheduler_gamma: 0.95
  test_batch_size: 1
  train_sum_dir: train_log
  val_batch_size: 1
  weight_decay: 0.001
